cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),



]

ewebapp/urls.py
from django.contrib import admin
from django.urls import path
from.import views

app_name='ewebapp'
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home),
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail,name='prodCatdetail')
]

ewebpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eweb/',include('ewebapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/' ,include('cart.urls'))
,]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.Search_Result, name='SearchResult')
]

cart/models.py
from django.db import models
from ewebapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)


    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ewebapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.CharField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self) :
        return reverse('ewebapp:product_by_category', args=[self.slug,])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=65,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self) :
        return reverse('ewebapp:prodCatdetail', args=[self.category.slug, self.slug])

    class Meta :
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self) :
        return '{}'.format(self.name)

search_app/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect
from ewebapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
             cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:  # Corrected variable name here
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ewebapp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
def home(request):
    return render(request,'home.html')

# def allProdCat(request,c_slug=None):
#     c_page=None
#     products=None
#     if c_slug!=None:
#         c_page=get_object_or_404(Category,slug=c_slug)
#         products=Product.objects.all().filter(Category=c_page,available=True)
#     else:
#         products=Product.objects.all().filter(available=True)
#     return render(request,'category.html',{'category':c_page,'products':products})

def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category': c_page, 'products': products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

search_app/views.py
from django.shortcuts import render
from ewebapp.models import Product
from django.db.models import Q

# Create your views here.
def Search_Result(request):
    products = None
    query = None
    if 'q' in request.GET:  # Fixed the syntax error here
        query = request.GET.get('q')
        products = Product.objects.filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/187c8d8a19.js" crossorigin="anonymous"></script>

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        {% include 'header.html' %}
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </div>

    {% include 'footer.html' %}

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
<div class="container">

</div>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Your Cart items
{% endblock %}
{% block title %}
    Cart - Eshopping
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    your shopping cart is empty
                </h1>
                <br>
                <p class="text-center">
                    please click <a href="{% url 'ewebapp:allProdCart' %}">Here</a> to continue shopping.
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    your shopping cart
                </h1>
                <br>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                Your Items
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{ cart_item.product.get_absolute_url }}"><img src="{{ cart_item.product.image.url }}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-left">
                                    {{ cart_item.product.name }}<br>
                                    SKU: {{ cart_item.product.id }}<br>
                                    Price: $ {{ cart_item.product.price }}<br>
                                    Qty: {{ cart_item.quantity }} x $ {{ cart_item }}
                                </td>
                                <td>
                                    $ {{ cart_item.sub_total }}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                                            <i class="fa-solid fa-plus custom_icon"></i>
                                        </a>
                                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                                            <i class="fa fa-minus custom_icon"></i>
                                        </a>
                                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                                            <i class="fa fa-trash custom_icon"></i>
                                        </a>
                                    </td>
                                {% else %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                                            <i class="fa-solid fa-plus custom_icon"></i>
                                        </a>

                                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                                            <i class="fa fa-minus custom_icon"></i>
                                        </a>
                                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                                           <i class="fa fa-trash custom_icon"></i>
                                        </a>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-end">
                <div class="text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                                <th>
                                    Checkout
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    please review your shopping items before proceeding with the order payment.
                                </td>
                            </tr>
                        <tr>
                            <td class="text-left">
                                Your Total is: <strong> {{ total }}
                            </strong>

                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="mx-auto">
                        <a href="{% url 'ewebapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_table">Continue shopping</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
    {% if category %}
       {{ category.description|truncatewords:155 }}
    {% else %}
        welcome to e shopping
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - E shopping
    {% else %}
        see our awesome collections - E shopping
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="my_row_class">
                <div class="mx-auto">


                <p><a href="{% url 'ewebapp:allProdCat' %}">Our product collection</a></p>
                </div>

            </div>
        </div>
    {% endif %}

    <div class="mx_auto">
        {% if category %}
            <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}">
        </div>
        <br>
        <div>
            <h1 class="text-center my_title">{{ category.name }}</h1>
            <p class="text-justify">{{ category.description }}</p>
        </div>
    {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products">
        </div>
        <br>
        <div>
            <h1 class="text-center my title">Our product collections</h1>
            <p class="text-justify">dfdfd</p>
        </div>
    {% endif %}

    <div class="container">
        <div class="row mx_auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                    <div class="card text-center" style="min-width:15rem;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url }}"></a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}"  class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

templates/footer.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>

<div>
    <p class="text-center">&copy; ABC tech pvt ltd. All rights Reserved</p>
</div>

</body>
</html>

templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'ewebapp:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logimage"></a>
  </center>
</header>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hi
</body>
</html>

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sample Page</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ewebapp:allProdCat' %}">Home <span class="sr-only">(current)</span></a>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Link</a>-->
<!--      </li>-->
      <li class="nav-item dropdown {% if 'ewebapp' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ewebapp:allProdCat' %}">All Products</a>
             {% for cat in links %}
          <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>
             {% endfor %}

        </div>`
      </li>
      <li class="nav-item">
        {% if item_count > 0 %}
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
  </div>
</nav>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>

templates/product.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
   {{ product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} - E shopping
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
  <div class="mx_auto">
      <p> <a href="{% url 'ewebapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
      <div class="container"></div>
  </div>
</div>
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{ product.name }}</h1>
            <p>${{ product.price }}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{ product.description }}</p>
            {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of stock</b></p>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

   We have a wide variety of products available

{% endblock %}
{% block title %}
   search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
        <div class="row mx_auto">
            {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
                    <div class="card text-center" style="min-width:15rem;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url }}"></a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
            <div class="row mx-auto"
            <p class="text-center my_search_text">0 results found</p>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}